# Generated by Django 4.1.3 on 2022-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.UUIDField(unique=True, verbose_name='Transaction Id')),
                ('store_id', models.CharField(default='aamarpaytest', max_length=200, verbose_name='Store Id')),
                ('signature_key', models.CharField(default='dbb74894e82415a2f7ff0ec3a97e4183', max_length=200, verbose_name='Signature Key')),
            ],
        ),
    ]
