# Generated by Django 4.1.3 on 2022-11-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transection_tran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transection',
            name='signature_key',
        ),
        migrations.RemoveField(
            model_name='transection',
            name='store_id',
        ),
        migrations.AddField(
            model_name='transection',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=15, verbose_name='Transection amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transection',
            name='cus_add1',
            field=models.CharField(default='Dhaka', max_length=100, verbose_name='Customer House No'),
        ),
        migrations.AddField(
            model_name='transection',
            name='cus_email',
            field=models.EmailField(default='monir@gmail.com', max_length=254, verbose_name='Customer Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transection',
            name='cus_name',
            field=models.CharField(default='monir', max_length=100, verbose_name='Customer Fullname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transection',
            name='cus_phone',
            field=models.CharField(default='+8801869519372', max_length=14, verbose_name='Customer Phone no'),
            preserve_default=False,
        ),
    ]
