# Generated by Django 4.1.3 on 2022-11-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_transection_signature_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transection',
            old_name='cus_add1',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='transection',
            old_name='cus_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='transection',
            old_name='cus_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='transection',
            old_name='cus_phone',
            new_name='customer_phone_no',
        ),
        migrations.RenameField(
            model_name='transection',
            old_name='amount',
            new_name='transection_amount',
        ),
        migrations.RenameField(
            model_name='transection',
            old_name='tran_id',
            new_name='transection_id',
        ),
    ]
