# Generated by Django 4.1.3 on 2022-11-14 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_cus_add1_transection_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transection',
            name='transection_status',
            field=models.CharField(choices=[(0, 'Payment Initiated'), (1, 'Payment Attempt'), (2, 'Payemnt Successful'), (3, 'Payment Canceled'), (4, 'Payment Charge-back'), (5, 'Payment on hold'), (6, 'Suspect fraud'), (7, 'Payment failed'), (8, 'Payment Refunded by bank'), (9, 'Payment Incomplete'), (10, 'Payment Refund'), (11, 'Payment Error'), (12, 'Payment Refund due to Chargeback lost'), (13, 'Customer Documents Missing')], default=0, max_length=20, verbose_name='Transection Status'),
        ),
        migrations.AddField(
            model_name='transection',
            name='transection_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Transection Time'),
            preserve_default=False,
        ),
    ]
