# Generated by Django 4.1.3 on 2022-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_transection_transection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='customer_address',
            field=models.CharField(default='Dhaka', max_length=100, verbose_name='Customer Address'),
        ),
    ]
